---
- name: Configure Ubuntu servers
  hosts: ubuntu_servers
  vars:
    localhost_install: false
  become: true
  become_user: root
  gather_facts: true
  roles:
    - role: check_os
    - role: install_dpdk
    - role: sudoer
